!!python/object:argparse.Namespace
arch: resnet18
batch_size: 256
data: ../datasets
dataset_name: mnist
device: !!python/object/apply:torch.device
- cuda
disable_cuda: false
epochs: 100
fp16_precision: false
gpu_index: 1
log_every_n_steps: 100
lr: 0.0003
n_views: 2
out_dim: 128
resume: ''
seed: null
temperature: 0.07
weight_decay: 0.0001
workers: 12
